services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - config.env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    environment:
      - TZ=Africa/Cairo   # ✅ ضبط المنطقة الزمنية لمصر